theme: jekyll-theme-slate

title: [PxConsult.tech]
description: [Chip design services. Let's make your idea real.]
author: PxConsult.tech
email: jan.pleskac@pxconsult.tech
github_username: plexj
github:
  is_project_page: false
